#!/bin/bash

# Slackware build script for nvidia-kernel

# Copyright 2007-2011 Heinz Wiesinger, Amsterdam, The Netherlands
# Copyright 2011-2017 Edward W. Koenig, Vancouver, WA, USA
# Copyright 2025-2026 Oleh Nykyforchyn, Ivano-Frankivsk, Ukraine
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Thanks to Robby Workman for suggestions to improve this script.

# See changelog.txt

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=nvidia-legacy304-kernel
VERSION=${VERSION:-304.137}
BUILD=${BUILD:-1}
TAG=${TAG:-_Nyk}
PKGTYPE=${PKGTYPE:-tgz}

KERNEL=${KERNEL:-$(uname -r)}
KERNELPATH=${KERNELPATH:-/lib/modules/${KERNEL}/build}

if [ ! -r $KERNELPATH/.config ] ; then
  echo "$KERNELPATH/.config not found, failed!"
  echo "A configured linux kernel needed"
  exit 1
fi

if [ ! -r $KERNELPATH/Module.symvers ] ; then
  echo "$KERNELPATH/Module.symvers not found, failed!"
  echo "A configured linux kernel needed"
  exit 1
fi

PKGVER=${VERSION}_$(echo $KERNEL | tr - _)

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ "$ARCH" = "i586" ]; then
  TARGET="x86"
  SRCSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  TARGET="x86"
  SRCSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  TARGET="x86_64"
fi

SRCNAM=NVIDIA-Linux-$TARGET-${VERSION}

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$PKGVER-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/Nyk}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP || exit 1
rm -rf $SRCNAM

(
sh $CWD/../$SRCNAM.run --extract-only || exit 1
cd $SRCNAM || exit 1
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

cat $CWD/patches/series.in | \
    sed 's/use-nv-kernel-ARCH.o_binary.patch//g' | \
(
cd kernel

mv Makefile.kbuild Makefile

$CWD/tools/get_configured304.sh
mv got_configured304.txt got_configured304.orig
$CWD/tools/get_defined304.sh
mv got_defined304.txt got_defined304.orig
cp Makefile Makefile.orig
cp conftest.sh conftest.orig

while read LINE ; do
  if [ "$LINE" == "" ] ; then
    continue
  fi
  if echo $LINE | egrep '^#' >/dev/null ; then
    continue
  fi
  if [ "$TARGET" = "x86" -a -r $CWD/patches/${LINE}32 ] ; then
    echo Applying patch ${LINE}32
    patch -p1 < $CWD/patches/${LINE}32
  else
    echo Applying patch $LINE
    patch -p1 < $CWD/patches/$LINE
  fi
done

$CWD/tools/get_configured304.sh
mv got_configured304.txt got_configured304.deb
$CWD/tools/get_defined304.sh
cp got_defined304.txt got_defined304.deb
cp Makefile Makefile.deb
cp conftest.sh conftest.deb

# Here are additional patches
patch -p2 < $CWD/nv-fms-extensions.patch
patch -p2 < $CWD/nv-write-cr4.patch
$CWD/tools/get_defined304.sh

$CWD/tools/split_conftest304.sh
$CWD/tools/collect_tests304.sh
mv conftest.new conftest.sh
$CWD/tools/get_configured304.sh
chmod +x conftest.sh
rm -f Makefile
mv Makefile.new Makefile.kbuild
)

(
  unset ARCH
  cd kernel || exit 1
  touch .nv-kernel.o.cmd
  sed -i "s|-DNDEBUG$|-DNDEBUG -Wno-error=return-type -Wno-error=implicit-function-declaration -Wno-sign-compare -fms-extensions|" Makefile.kbuild
  make SYSSRC=$KERNELPATH module || exit 1
)

mkdir -p $PKG/lib/modules/$KERNEL/kernel/drivers/video
install -m 0664 kernel/nvidia.ko $PKG/lib/modules/$KERNEL/kernel/drivers/video/

# Make sure the X is specified to automagically load the
# correct driver, since I always forget. You can remove
# this file if you have an equivalent entry in /etc/X11/xorg.d

#mkdir -p $PKG/usr/share/X11/xorg.conf.d/
#cat $CWD/10-nvidia.conf > $PKG/usr/share/X11/xorg.conf.d/10-nvidia.conf

mkdir -p $PKG/usr/doc/$PRGNAM-$PKGVER
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$PKGVER/$PRGNAM.SlackBuild

mkdir -p $PKG/usr/sbin
install -m 700 $CWD/nvidia-prepare-boot $PKG/usr/sbin

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
sed "s%@KERNEL@%$KERNEL%" $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$PKGVER-$ARCH-$BUILD$TAG.$PKGTYPE
mv $OUTPUT/$PRGNAM-$PKGVER-$ARCH-$BUILD$TAG.$PKGTYPE $CWD/
) 2>&1 | tee $CWD/$PRGNAM-$PKGVER-$ARCH-$BUILD$TAG.log
